# if spring.profiles=name is not mention then that is global property
# If you are not using eureka or spring.cloud then put spring.port in application.yml
server:
  port: 9093
# we can set active profile from here as well no need to pass at run time
spring:
  profiles:
    active: h2,eureka
#  main:
#    banner-mode: "off"
# info property details shows in actuators info url http://localhost:8760/actuator/info
info:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'
  id: rds
  artifactId: '@project.artifactId@'
  packaging: '@project.packaging@'
  groupId: '@project.groupId@'

# If you want to consumed Actuator restricted command but upto 1.x.x actuator version 
#management:
#  security:
#    enabled: false
# From 2.x.x you need to use below properties to enable restricted endpoints of actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
#        - env
        - beans
